spring.application.name=back-end

# ==========================================
# CONEXÃO COM MYSQL
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/db_manu?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# PORTA DO SPRING BOOT
# ==========================================

server.port=8080